name: Overcloud

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.18.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Golang info
      run: go version

    - name: Format code
      run: |
        go fmt ./auth
        go fmt ./model

    - name: Vet source code
      run: go vet -c=3 -json ./auth

    #- name: Get dependencies and create binary
    #  run: |
    #    go get -d ./auth
    #    go build -o auth ./auth

    - name: Run tests
      run: |
        # go test -v ./auth -run TestValidResponseData
        go test -v ./auth -run TestInvalidResponseData
        go test -v ./auth -run TestCredentialsPresent
        go test -v ./auth -run TestCredentialsAbsent
        go test ./auth -race -coverprofile=profile.out -covermode=atomic

    #- name: Compute coverage, output data and create report
    #  run: |
    #    go test -v ./auth -coverprofile profile.out
    #    go tool cover -func profile.out
    #    go tool cover -html=profile.out -o coverage.html
